homework 4.1
Kolesa-Education/kolesa-upgrade-homework-4 pull request #12
Opened 2022-09-28 10:15 UTC by AidanaErb

2022-09-29 05:34 UTC, YerkebulanAben reviewed
Меня смущают следующие моменты:
1) Почему связь между кораблем и полетом 1-к-1
2) Почему связь между полетами и планетой тоже 1-к-1

2022-09-29 10:22 UTC, YerkebulanAben commented
принимаю твое дз, молодец

2022-09-29 10:41 UTC, YerkebulanAben reviewed
я как понял у тебя в таблице Film PK это id_film, а FK producer_id?

2022-09-29 10:48 UTC, AidanaErb commented
Я хотела добавить составной ключ, который состоит из самого id фильма и id режиссера. Но сейчас я понимаю, что это неправильно. Чтобы сделать составной ключ стоило добавить id_producer + название_фильма и это было бы PK

2022-09-29 11:28 UTC, YerkebulanAben commented
> Я хотела добавить составной ключ, который состоит из самого id фильма и id режиссера. Но сейчас я понимаю, что это неправильно. Чтобы сделать составной ключ стоило добавить id_producer + название_фильма и это было бы PK

Ну тут у тебя id фильма уже первичный ключ. Зачем его делать составным? ID фильма ведь и так не будет повторяться у тебя в талблице)

2022-10-02 13:28 UTC, YerkebulanAben requested changes
1) У тебя студент может учиться только в одном университете, но у людей может быть 2 высших)
2) Нету понимания, кто ментор, кто лектор, а кто тот и тот.В твоей схеме получается, что если я лектор, то я и ментором обязан быть
3) У тебя в таблице с ДЗ ПК это  id лекции, что не логично немного. Из-за этого у тебя и в таблице с прогрессом немного все поехало)

2022-10-03 08:43 UTC, YerkebulanAben reviewed
1) хоть связь между студентом и универом многие-ко-многим, но не показана таблица через которую они связаны
2) странно, что ты сделала ПК лекций дату их проведения. Получается, что у тебя не может быть 2-ух лекций в одну дату. В данном контексте это вроде норм, но так лучше не делать)

2022-10-04 04:59 UTC, closed without merging