Tagaev homework 4
Kolesa-Education/kolesa-upgrade-homework-4 pull request #22
Opened 2022-09-28 14:22 UTC by thefastest2snail

2022-09-29 05:50 UTC, YerkebulanAben reviewed
Вопросы:
1) Зачем нужна таблица SpaceX?)
2) Что за distance в таблице flights?
3) У тебя таблица Фильмы не соответствует 3 НФ, подумай, что не так)
4) Не понятно как у тебя связаны таблицы Сеансы и Билеты. Нет внешнего ключа

2022-09-29 07:14 UTC, YerkebulanAben commented
Молодец! Принимаю твою работу

2022-09-29 07:38 UTC, thefastest2snail commented
> Молодец! Принимаю твою работу

Спасибо!

2022-10-02 05:06 UTC, YerkebulanAben requested changes
1) У тебя таблица ролей очень странная. Может надо разбить ее на просто ментор, лектор
2) Где учился студент у тебя это просто строка в таблице. Возможно лучше вынести в отдельную таблицу этот момент. Также студент может иметь 2 высших образования))
3) Лучше наверное в ДЗ указать, к какой лекции она относится, так как  не у всех лекций есть ДЗ

2022-10-02 13:38 UTC, YerkebulanAben requested changes
1) По поводу ролей сотрудников имел ввиду в одну таблицу все написать, как ваще роли есть. И потом через связь многи ко многим это раскидать
2) У тебя у студента только одно высшее образрвание может быть, а ведь он/она может иметь 2 высших образования. Здесь такая же ошибка как и с менторами и лекторами выше)
3) Таблица с результатами немного странная. Там ПК это тот же ПК, что и в ДЗ, надо сделать их независимыми друг от друга, ПК в ДЗ и ПК в прогрессе выполнения)

2022-10-02 14:30 UTC, YerkebulanAben reviewed
Принимаю ДЗ. Чтобы вообще все по красоте было можно связь между ментором и студентом в отдлеьную таблицу вынести

2022-10-04 04:59 UTC, closed without merging