Выполнил задание 4-1
Kolesa-Education/kolesa-upgrade-homework-4 pull request #27
Opened 2022-09-28 16:36 UTC by eugenenazirov

2022-09-29 05:55 UTC, YerkebulanAben reviewed
Молодец, хорошо все сделал! Принимаю твою работу)

2022-09-29 05:56 UTC, eugenenazirov commented
Круто. Спасибо!

2022-10-02 05:00 UTC, YerkebulanAben requested changes
1) У тебя один студент учится/учился только в одном универе. Хотя у него может быть 2 высших)))
2) У тебя сотрудник может быть только ментором или лектором
3) Наверное лучше было бы в ДЗ сделать ссылку на лекцию, так как не у всех лекций есть ДЗ

2022-10-02 10:15 UTC, YerkebulanAben reviewed
Молодец! Принимаю ДЗ

2022-10-04 04:58 UTC, closed without merging