выполняю задание 4
Kolesa-Education/kolesa-upgrade-homework-4 pull request #37
Opened 2022-09-29 06:18 UTC by resar3ct

2022-09-29 07:08 UTC, YerkebulanAben reviewed
У тебя в таблице с билетами прописаны имена, фамилии покупателей и телефон. Подумай, что там не так)
3 ДЗ я позже проверю. По идее я должен был ее после 2-ой лекции только дать)

2022-09-29 08:14 UTC, resar3ct commented
"У тебя в таблице с билетами прописаны имена, фамилии покупателей и телефон" - я должен был в отдельную таблицу вынести?

2022-09-29 08:40 UTC, YerkebulanAben reviewed
Молодец, принимаю твое ДЗ!

2022-10-02 04:52 UTC, YerkebulanAben requested changes
Насчет второй части ДЗ:
1) В таблице студентов можно было не писать, учится он сейчас или нет, так как такая инфа уже есть в таблице, где какой студент учился/учится (не критично)
2) Отношения между менторами и студентами можно было в отдельную таблицу вынести, чтобы вообще все красиво было) (не критично)
3) в твоей БД сотрудник может быть только ментором или лектором
4) у тебя нет автора ДЗ.
Надо исправить замечания, чтобы я принял ДЗ

2022-10-03 08:50 UTC, YerkebulanAben reviewed
забыл указать связь между домашкой и лекцией, а так все хорошо

2022-10-03 09:02 UTC, resar3ct commented
хорошо, спасибо

2022-10-04 04:59 UTC, closed without merging