sorry for being late
Kolesa-Education/kolesa-upgrade-homework-4 pull request #57
Opened 2022-09-29 17:05 UTC by salawhaaat

sorry for being late

2022-09-30 03:38 UTC, tungatarovKl approved these changes
дз принято

2022-10-03 03:42 UTC, tungatarovKl requested changes
Тут с таблицой СотрудникРоль будет трабл. Например 1 и тот же роль допустим ментор будет повторятся несколько раз для каждого студента, более правильнее сделать через 3-ию таблицу
В остальном все хорошо

2022-10-03 18:47 UTC, salawhaaat commented
Я вроде решил проблему

2022-10-04 04:12 UTC, tungatarovKl approved these changes

2022-10-08 18:29 UTC, closed without merging